version: 0.2

phases:

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp

  build:
    commands:
      - docker build -t dockerapp .
      - docker tag dockerapp:latest 010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp:latest
      - docker push 010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp:latest
artifacts:
  files:
    - '**/*'  
  