version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      # - docker build -t dockerapp .
      - docker build --platform linux/amd64 -t dockerapp .
      - docker tag dockerapp:latest 010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 010928179293.dkr.ecr.us-east-1.amazonaws.com/dockerapp:latest 
artifacts:
    files: imagedefinitions.json