version: 0.2

phases:

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010928179293.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t akashshinde/docapp .
      - docker tag akashshinde/docapp:latest 010928179293.dkr.ecr.us-east-1.amazonaws.com/akashshinde/docapp:latest
      - docker push 010928179293.dkr.ecr.us-east-1.amazonaws.com/akashshinde/docapp:latest
artifacts:
  files:
    - '**/*'  
  